# Generated by Django 5.2.5 on 2025-09-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_song_file_path_song_audio_file_song_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='song',
            name='image',
        ),
        migrations.RemoveField(
            model_name='song',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='song',
            name='album_art',
            field=models.ImageField(blank=True, null=True, upload_to='album_arts/'),
        ),
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(default='default.mp3', upload_to='songs/'),
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
