# Generated by Django 5.2.5 on 2025-09-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_song_album_remove_song_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(default='songs/default.mp3', max_length=500, upload_to='songs/'),
        ),
    ]
